{% set name = "pastescript" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PasteScript-{{ version }}.tar.gz
  sha256: 1c22d2b7cd5351646beed28c6f70eb4a2a4b925651d9afcaa3501d06cabb5171

build:
  entry_points:
    - paster = paste.script.command:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - paste >=3.0
    - pastedeploy
    - six
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - paste
    - paste.script
    - paste.script.util
  commands:
    - paster -h

about:
  home: http://pythonpaste.org/script/
  license: MIT
  summary: A pluggable command-line frontend, including commands to setup package file layouts
  license_file: docs/license.txt

extra:
  recipe-maintainers:
    - ocefpaf
