{% set name = "pastescript" %}
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PasteScript-{{ version }}.tar.gz
  sha256: cd1b606cd45e9684ffdb448bd6d9aaef420dd2efe7e6b62c6d373a46ff43c835

build:
  entry_points:
    - paster = paste.script.command:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - paste >=3.0
    - pastedeploy
    - six
    - setuptools

test:
  imports:
    - paste
    - paste.script
    - paste.script.util
  commands:
    - paster -h

about:
  home: http://pythonpaste.org/script/
  license: MIT
  summary: A pluggable command-line frontend, including commands to setup package file layouts
  license_file: docs/license.txt

extra:
  recipe-maintainers:
    - ocefpaf
