{% set version = "3.4.0" %}

package:
  name: pastescript
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PasteScript/PasteScript-{{ version }}.tar.gz
  sha256: 9348ef065aff22cf1588c12dfb020cc751c6482e216f8a3c7512fa40a43f90dc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - paster = paste.script.command:run

requirements:
  host:
    - python >=3.6
    - pip
    - paste >=3
    - pastedeploy
    - six
  run:
    - python >=3.6
    - paste >=3.0
    - pastedeploy
    - setuptools
    - six

test:
  imports:
    - paste
    - paste.script
    - paste.script.util
  commands:
    - paster -h

about:
  home: http://pythonpaste.org/script/
  license: MIT
  summary: A pluggable command-line frontend, including commands to setup package file layouts
  license_file: docs/license.txt

extra:
  recipe-maintainers:
    - ocefpaf
